services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_NAME=data_ingestion
      - DB_USER=readonlyuser
      - DB_PASSWORD=readonlypassword
    depends_on:
      db:
        condition: service_healthy
